import { SpeedInsights } from "@vercel/speed-insights/next";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";

import "@/shared/styles/globals.css";
import { Providers } from "@/providers";
import type { LayoutProps } from "@/shared/types/next";

const interSans = Inter({
	variable: "--font-inter-sans",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children, params }: LayoutProps) {
	return (
		<html lang="en">
			<body className={`${interSans.variable} antialiased`}>
				<Providers>
					<main className="flex min-h-screen">{children}</main>
					<Toaster
						position="top-center"
						reverseOrder={false}
						toastOptions={{
							duration: 4000,
							className: "py-5! px-8! text-base font-medium",
						}}
					/>
					<SpeedInsights />
				</Providers>
			</body>
		</html>
	);
}
